// <auto-generated />
using System;
using HR_SYSTEM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HR_SYSTEM.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20221116072357_employeeimage")]
    partial class employeeimage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HR_SYSTEM.Models.ANR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AreaUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AreaofEnclosure")
                        .HasColumnType("int");

                    b.Property<int>("AverageRegeneration")
                        .HasColumnType("int");

                    b.Property<string>("DamageReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofActivity")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateofEnclosure")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstablishmentMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedDamage")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedDamageAcreage")
                        .HasColumnType("int");

                    b.Property<string>("EstimatedSuccess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeySpecies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongTermMeasures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MajorInterventions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Neghaban")
                        .HasColumnType("int");

                    b.Property<string>("PlanForSbstitution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProtectionMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkilledLabour")
                        .HasColumnType("int");

                    b.Property<int>("TotalRegeneration")
                        .HasColumnType("int");

                    b.Property<string>("UDCSolution")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ANRs");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Company", b =>
                {
                    b.Property<int>("CompanyRegNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandlineNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyRegNo");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pakistan"
                        });
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Department", b =>
                {
                    b.Property<int>("DepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CompanyRegNo")
                        .HasColumnType("int");

                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandlineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepId");

                    b.HasIndex("CompanyRegNo");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyRegNo")
                        .HasColumnType("int");

                    b.Property<int>("DepId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("EmpId");

                    b.HasIndex("DepId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.MobileNo", b =>
                {
                    b.Property<int>("MobileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CompanyRegNo")
                        .HasColumnType("int");

                    b.Property<int>("DepId")
                        .HasColumnType("int");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MobileId");

                    b.HasIndex("EmpId");

                    b.ToTable("MobileNumbers");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Tehsil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Tehsils");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Department", b =>
                {
                    b.HasOne("HR_SYSTEM.Models.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyRegNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.District", b =>
                {
                    b.HasOne("HR_SYSTEM.Models.Division", "Divisions")
                        .WithMany("Districts")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Division", b =>
                {
                    b.HasOne("HR_SYSTEM.Models.Province", "Provinces")
                        .WithMany("Divisions")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Employee", b =>
                {
                    b.HasOne("HR_SYSTEM.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_SYSTEM.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.MobileNo", b =>
                {
                    b.HasOne("HR_SYSTEM.Models.Employee", "Employee")
                        .WithMany("MobileNos")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Province", b =>
                {
                    b.HasOne("HR_SYSTEM.Models.Country", "Countries")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Countries");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Tehsil", b =>
                {
                    b.HasOne("HR_SYSTEM.Models.District", "Districts")
                        .WithMany("Tehsils")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Company", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Country", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.District", b =>
                {
                    b.Navigation("Tehsils");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Division", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Employee", b =>
                {
                    b.Navigation("MobileNos");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Province", b =>
                {
                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("HR_SYSTEM.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
